// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export namespace store {

	export class SaveResult {
		conflict: boolean;
		rev: number;
		static createFrom(source: any = {}): SaveResult {
			return new SaveResult(source);
		}
		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this.conflict = source["conflict"];
			this.rev = source["rev"];
		}
	}

	export class Scenario {
		id: string;
		title: string;
		system: string;
		players: string;
		playTime: string;
		meta: string;
		createdAt: number;
		updatedAt: number;
		static createFrom(source: any = {}): Scenario {
			return new Scenario(source);
		}
		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this.id = source["id"];
			this.title = source["title"];
			this.system = source["system"];
			this.players = source["players"];
			this.playTime = source["playTime"];
			this.meta = source["meta"];
			this.createdAt = source["createdAt"];
			this.updatedAt = source["updatedAt"];
		}
	}

	export class SectionMeta {
		id: string;
		scenarioId: string;
		parentId: string;
		kind: string;
		title: string;
		sortKey: string;
		rev: number;
		updatedAt: number;
		static createFrom(source: any = {}): SectionMeta {
			return new SectionMeta(source);
		}
		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this.id = source["id"];
			this.scenarioId = source["scenarioId"];
			this.parentId = source["parentId"];
			this.kind = source["kind"];
			this.title = source["title"];
			this.sortKey = source["sortKey"];
			this.rev = source["rev"];
			this.updatedAt = source["updatedAt"];
		}
	}

	export class Section {
		id: string;
		scenarioId: string;
		parentId: string;
		kind: string;
		title: string;
		body: string;
		sortKey: string;
		rev: number;
		updatedAt: number;
		static createFrom(source: any = {}): Section {
			return new Section(source);
		}
		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
			this.id = source["id"];
			this.scenarioId = source["scenarioId"];
			this.parentId = source["parentId"];
			this.kind = source["kind"];
			this.title = source["title"];
			this.body = source["body"];
			this.sortKey = source["sortKey"];
			this.rev = source["rev"];
			this.updatedAt = source["updatedAt"];
		}
	}

	export class Store {
		static createFrom(source: any = {}): Store {
			return new Store(source);
		}
		constructor(source: any = {}) {
			if ('string' === typeof source) source = JSON.parse(source);
		}
	}

}
