// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AckFlush() {
  return window['go']['main']['App']['AckFlush']();
}

export function CreateSection(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateSection'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteSection(arg1) {
  return window['go']['main']['App']['DeleteSection'](arg1);
}

export function GetSection(arg1) {
  return window['go']['main']['App']['GetSection'](arg1);
}

export function ListSections(arg1) {
  return window['go']['main']['App']['ListSections'](arg1);
}

export function MoveSection(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveSection'](arg1, arg2, arg3);
}

export function OpenScenario() {
  return window['go']['main']['App']['OpenScenario']();
}

export function SaveSection(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSection'](arg1, arg2, arg3);
}
