// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function AckFlush():Promise<void>;

export function CreateSection(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<store.SectionMeta>;

export function DeleteSection(arg1:string):Promise<void>;

export function GetSection(arg1:string):Promise<store.Section>;

export function ListSections(arg1:string):Promise<Array<store.SectionMeta>>;

export function MoveSection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenScenario():Promise<store.Scenario>;

export function SaveSection(arg1:string,arg2:string,arg3:number):Promise<store.SaveResult>;
