// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function AckFlush():Promise<void>;
export function CreateSection(scenarioID:string,parentID:string,kind:string,title:string,afterID:string):Promise<store.SectionMeta>;
export function DeleteSection(id:string):Promise<void>;
export function GetSection(id:string):Promise<store.Section>;
export function ListSections(scenarioID:string):Promise<Array<store.SectionMeta>>;
export function MoveSection(id:string,newParentID:string,afterID:string):Promise<void>;
export function OpenScenario():Promise<store.Scenario>;
export function SaveSection(id:string,body:string,rev:number):Promise<store.SaveResult>;
export function Store():Promise<store.Store>;
