// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AckFlush() {
  return window['go']['main']['App']['AckFlush']();
}

export function CreateSection(scenarioID, parentID, kind, title, afterID) {
  return window['go']['main']['App']['CreateSection'](scenarioID, parentID, kind, title, afterID);
}

export function DeleteSection(id) {
  return window['go']['main']['App']['DeleteSection'](id);
}

export function GetSection(id) {
  return window['go']['main']['App']['GetSection'](id);
}

export function ListSections(scenarioID) {
  return window['go']['main']['App']['ListSections'](scenarioID);
}

export function MoveSection(id, newParentID, afterID) {
  return window['go']['main']['App']['MoveSection'](id, newParentID, afterID);
}

export function OpenScenario() {
  return window['go']['main']['App']['OpenScenario']();
}

export function SaveSection(id, body, rev) {
  return window['go']['main']['App']['SaveSection'](id, body, rev);
}

export function Store() {
  return window['go']['main']['App']['Store']();
}
